import { Heightmap } from "../core/heightmap";

export class RawExporter {
  /**
   * Exports raw Float32Array binary data.
   */
  public static downloadRaw(heightmap: Heightmap, filename = "terrain_elevation_f32.raw"): void {
    const bytes = new Uint8Array(heightmap.data.buffer);
    const blob = new Blob([bytes.buffer as ArrayBuffer], { type: "application/octet-stream" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  /**
   * Exports terrain geometry as a Wavefront OBJ mesh file.
   * Can be imported directly into Blender, Maya, Unreal, Unity.
   */
  public static downloadOBJ(heightmap: Heightmap, worldSize = 500, filename = "terrain_mesh.obj"): void {
    const res = heightmap.resolution;
    const data = heightmap.data;
    const step = worldSize / (res - 1);
    const half = worldSize * 0.5;

    let obj = "# Wavefront OBJ generated by Physically-Based Terrain Erosion Engine\n";
    obj += `o Terrain_${res}x${res}\n`;

    for (let y = 0; y < res; y++) {
      const pz = y * step - half;
      const v = y / (res - 1);
      const row = y * res;
      for (let x = 0; x < res; x++) {
        const px = x * step - half;
        const py = data[row + x];
        const u = x / (res - 1);
        obj += `v ${px.toFixed(2)} ${py.toFixed(2)} ${pz.toFixed(2)}\n`;
        obj += `vt ${u.toFixed(4)} ${v.toFixed(4)}\n`;
      }
    }

    for (let y = 0; y < res - 1; y++) {
      for (let x = 0; x < res - 1; x++) {
        const i0 = y * res + x + 1;
        const i1 = y * res + (x + 1) + 1;
        const i2 = (y + 1) * res + (x + 1) + 1;
        const i3 = (y + 1) * res + x + 1;

        obj += `f ${i0}/${i0} ${i1}/${i1} ${i2}/${i2}\n`;
        obj += `f ${i0}/${i0} ${i2}/${i2} ${i3}/${i3}\n`;
      }
    }

    const blob = new Blob([obj], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
}
